import type { FoodAnalysis, Ingredient, MenuAnalysis, MenuItemAnalysis } from "../types";
import { generateId } from "../utils";

export function getDemoFoodAnalysis(imageDataUrl?: string): FoodAnalysis {
  const id = generateId();
  return {
    id,
    dishName: "Grilled Chicken Salad",
    confidence: 0.92,
    summary:
      "A fresh grilled chicken salad with mixed greens, cherry tomatoes, cucumbers, and a light vinaigrette dressing. This dish is high in protein and low in carbs, making it a great option for a healthy meal.",
    imageUrl: imageDataUrl,
    ingredients: [
      {
        name: "Chicken Breast",
        category: "protein",
        estimatedQuantity: "150g",
        calories: 247,
        allergens: [],
        notes: "Lean protein source, grilled preparation",
        substitutions: ["tofu", "turkey", "chickpeas"],
      },
      {
        name: "Mixed Greens",
        category: "vegetable",
        estimatedQuantity: "100g",
        calories: 25,
        allergens: [],
        notes: "Rich in fiber, vitamins A and C",
        substitutions: ["spinach", "kale", "arugula"],
      },
      {
        name: "Cherry Tomatoes",
        category: "vegetable",
        estimatedQuantity: "80g",
        calories: 14,
        allergens: [],
        notes: "Good source of lycopene and vitamin C",
        substitutions: ["sun-dried tomatoes", "roasted red peppers"],
      },
      {
        name: "Cucumber",
        category: "vegetable",
        estimatedQuantity: "60g",
        calories: 8,
        allergens: [],
        notes: "Hydrating and low calorie",
        substitutions: ["zucchini", "celery"],
      },
      {
        name: "Olive Oil Vinaigrette",
        category: "sauce",
        estimatedQuantity: "30ml",
        calories: 119,
        allergens: [],
        notes: "Healthy fats from olive oil",
        substitutions: ["balsamic vinaigrette", "lemon juice"],
      },
      {
        name: "Croutons",
        category: "carb",
        estimatedQuantity: "20g",
        calories: 77,
        allergens: ["gluten"],
        notes: "Adds texture and crunch",
        substitutions: ["nuts", "seeds", "gluten-free croutons"],
      },
    ],
    nutrition: {
      calories: 490,
      protein: 42,
      carbs: 18,
      fat: 28,
      sodium: 520,
      sugar: 6,
    },
    dietaryTags: [
      "high-protein",
      "low-carb",
      "dairy-free",
      "nut-free",
    ],
    allergenWarnings: ["Contains gluten (croutons)"],
    healthScore: 82,
    hiddenIngredients: [
      "Sugar (in vinaigrette)",
      "Natural flavors",
    ],
    confidenceNotes: "High confidence based on clear image analysis. Crouton gluten detected with moderate confidence.",
    createdAt: new Date().toISOString(),
  };
}

export function getAlternativeDemos(): FoodAnalysis[] {
  const base = getDemoFoodAnalysis();
  const alt1: FoodAnalysis = {
    ...base,
    id: generateId(),
    dishName: "Spaghetti Bolognese",
    confidence: 0.88,
    summary:
      "Classic spaghetti with a rich meat-based tomato sauce, seasoned with herbs and garlic. A hearty Italian dish.",
    ingredients: [
      {
        name: "Spaghetti Pasta",
        category: "carb",
        estimatedQuantity: "200g",
        calories: 300,
        allergens: ["gluten"],
        notes: "Durum wheat semolina pasta",
        substitutions: ["gluten-free pasta", "zucchini noodles"],
      },
      {
        name: "Ground Beef",
        category: "protein",
        estimatedQuantity: "150g",
        calories: 330,
        allergens: [],
        notes: "Grass-fed beef recommended",
        substitutions: ["ground turkey", "lentils", "plant-based mince"],
      },
      {
        name: "Tomato Sauce",
        category: "sauce",
        estimatedQuantity: "120ml",
        calories: 45,
        allergens: [],
        notes: "San Marzano tomatoes, garlic, herbs",
        substitutions: ["arrabbiata sauce", "pesto"],
      },
      {
        name: "Parmesan Cheese",
        category: "dairy",
        estimatedQuantity: "20g",
        calories: 86,
        allergens: ["dairy", "milk"],
        notes: "Aged hard cheese, adds umami",
        substitutions: ["nutritional yeast", "vegan parmesan"],
      },
      {
        name: "Garlic",
        category: "seasoning",
        estimatedQuantity: "10g",
        calories: 4,
        allergens: [],
        notes: "Aromatic base, adds depth",
        substitutions: ["garlic powder", "shallots"],
      },
      {
        name: "Olive Oil",
        category: "oil",
        estimatedQuantity: "15ml",
        calories: 119,
        allergens: [],
        notes: "Extra virgin olive oil",
        substitutions: ["avocado oil"],
      },
    ],
    nutrition: {
      calories: 884,
      protein: 38,
      carbs: 62,
      fat: 52,
      sodium: 780,
      sugar: 12,
    },
    dietaryTags: ["high-protein"],
    allergenWarnings: ["Contains gluten (pasta)", "Contains dairy (parmesan)"],
    healthScore: 58,
    hiddenIngredients: ["Sugar (in sauce)", "Whey (in pasta)"],
    confidenceNotes: "Good confidence. Pasta and sauce clearly identified.",
    createdAt: new Date().toISOString(),
  };

  const alt2: FoodAnalysis = {
    ...base,
    id: generateId(),
    dishName: "Vegan Buddha Bowl",
    confidence: 0.95,
    summary:
      "A nourishing bowl packed with quinoa, roasted sweet potatoes, chickpeas, avocado, and tahini dressing. Completely plant-based and nutrient-dense.",
    ingredients: [
      {
        name: "Quinoa",
        category: "carb",
        estimatedQuantity: "150g",
        calories: 180,
        allergens: [],
        notes: "Complete protein, high in fiber",
        substitutions: ["brown rice", "farro", "cauliflower rice"],
      },
      {
        name: "Sweet Potato",
        category: "vegetable",
        estimatedQuantity: "150g",
        calories: 129,
        allergens: [],
        notes: "Rich in beta-carotene and vitamin A",
        substitutions: ["butternut squash", "regular potato"],
      },
      {
        name: "Chickpeas",
        category: "protein",
        estimatedQuantity: "100g",
        calories: 164,
        allergens: [],
        notes: "Excellent plant protein and fiber source",
        substitutions: ["lentils", "black beans", "tofu"],
      },
      {
        name: "Avocado",
        category: "vegetable",
        estimatedQuantity: "80g",
        calories: 128,
        allergens: [],
        notes: "Healthy monounsaturated fats",
        substitutions: ["hummus", "olive oil dressing"],
      },
      {
        name: "Tahini Dressing",
        category: "sauce",
        estimatedQuantity: "30ml",
        calories: 89,
        allergens: ["sesame"],
        notes: "Sesame seed paste based dressing",
        substitutions: ["lemon vinaigrette", "avocado dressing"],
      },
    ],
    nutrition: {
      calories: 690,
      protein: 22,
      carbs: 68,
      fat: 36,
      sodium: 340,
      sugar: 14,
    },
    dietaryTags: [
      "vegan",
      "vegetarian",
      "gluten-free",
      "dairy-free",
      "nut-free",
      "high-protein",
    ],
    allergenWarnings: ["Contains sesame (tahini)"],
    healthScore: 91,
    hiddenIngredients: [],
    confidenceNotes: "Very high confidence. All ingredients clearly visible.",
    createdAt: new Date().toISOString(),
  };

  return [alt1, alt2];
}

export function getDemoMenuAnalysis(text?: string): MenuAnalysis {
  return {
    restaurantName: "The Green Table Bistro",
    items: [
      {
        name: "Classic Caesar Salad",
        description:
          "Romaine lettuce, parmesan, croutons, house-made caesar dressing",
        likelyIngredients: [
          "romaine lettuce",
          "parmesan cheese",
          "croutons",
          "olive oil",
          "garlic",
          "anchovies",
          "egg yolk",
          "lemon juice",
        ],
        estimatedNutrition: { calories: 450, protein: 12, carbs: 20, fat: 36 },
        allergens: ["dairy", "gluten", "eggs", "fish"],
        dietaryTags: ["vegetarian"],
        healthScore: 55,
      },
      {
        name: "Grilled Salmon Plate",
        description:
          "Atlantic salmon fillet, roasted asparagus, lemon butter sauce, wild rice",
        likelyIngredients: [
          "salmon",
          "asparagus",
          "butter",
          "lemon",
          "wild rice",
          "garlic",
          "dill",
        ],
        estimatedNutrition: { calories: 620, protein: 45, carbs: 32, fat: 32 },
        allergens: ["fish", "dairy"],
        dietaryTags: ["gluten-free", "high-protein", "nut-free"],
        healthScore: 78,
      },
      {
        name: "Truffle Mushroom Risotto",
        description:
          "Arborio rice, wild mushrooms, truffle oil, parmesan, fresh thyme",
        likelyIngredients: [
          "arborio rice",
          "mixed wild mushrooms",
          "truffle oil",
          "parmesan cheese",
          "butter",
          "shallots",
          "white wine",
          "vegetable stock",
        ],
        estimatedNutrition: { calories: 580, protein: 14, carbs: 68, fat: 28 },
        allergens: ["dairy", "alcohol"],
        dietaryTags: ["vegetarian", "gluten-free", "nut-free"],
        healthScore: 62,
      },
      {
        name: "Spicy Thai Noodle Bowl",
        description:
          "Rice noodles, peanut sauce, shredded carrots, bell peppers, cilantro, lime",
        likelyIngredients: [
          "rice noodles",
          "peanut butter",
          "coconut milk",
          "soy sauce",
          "carrots",
          "bell peppers",
          "cilantro",
          "lime",
          "chili flakes",
          "ginger",
        ],
        estimatedNutrition: { calories: 520, protein: 16, carbs: 62, fat: 26 },
        allergens: ["peanuts", "soy"],
        dietaryTags: ["vegan", "vegetarian", "gluten-free", "dairy-free", "spicy"],
        healthScore: 65,
      },
      {
        name: "Grass-Fed Beef Burger",
        description:
          "Angus beef patty, brioche bun, aged cheddar, lettuce, tomato, onion jam",
        likelyIngredients: [
          "angus beef",
          "brioche bun",
          "cheddar cheese",
          "lettuce",
          "tomato",
          "onion jam",
          "pickles",
          "mustard",
        ],
        estimatedNutrition: { calories: 850, protein: 48, carbs: 42, fat: 52 },
        allergens: ["gluten", "dairy", "mustard"],
        dietaryTags: ["nut-free", "high-protein"],
        healthScore: 42,
      },
      {
        name: "Vegan Power Bowl",
        description:
          "Quinoa, roasted chickpeas, avocado, kale, pickled onions, lemon-tahini dressing",
        likelyIngredients: [
          "quinoa",
          "chickpeas",
          "avocado",
          "kale",
          "red onion",
          "tahini",
          "lemon juice",
          "olive oil",
        ],
        estimatedNutrition: { calories: 510, protein: 18, carbs: 54, fat: 26 },
        allergens: ["sesame"],
        dietaryTags: [
          "vegan",
          "vegetarian",
          "gluten-free",
          "dairy-free",
          "nut-free",
        ],
        healthScore: 88,
      },
    ],
  };
}
