name: Optional CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-current-template:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: templates/gamified-path-version

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: templates/gamified-path-version/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build current template
        run: npm run build
